import "./globals.css";

import AuthProvider from "@/providers/AuthProviders";

export const metadata = {
  title: "JRF ASSETS MANAGER",
  description: "Generated by JRF Intel BD",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
